apiVersion: v2
name: grt-times
description: A Helm chart for the GRT Vehicle Positions API
type: application
version: 0.2.0
appVersion: "0.2.0"
maintainers:
  - name: John Steel
keywords:
  - grt
  - gtfs
  - transit
